apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: harbor.shared-services.home.pcfdot.com/library/spc:latest
        name: spc
        env:
          - name: spring.profiles.active
            value: mysql
          - name: MYSQL_USER
            value: petclinic
          - name: MYSQL_PASS
            value: petclinic
          - name: MYSQL_URL
            value: jdbc:mysql://mysql.default.svc.cluster.local/petclinic
        ports:
        - containerPort: 8080
          
